### ISSUE TITLE
I can not get value from context to write log.

### ISSUE THREAD

**Issue by nguyenquangtrung** [r2dbc/r2dbc-proxy#119]
How to get value from context.
<pattern>[%date{yyyy/MM/ddHH:mm:ss.SSS}]\t%-5level\t%X{MARKER}\t%X{X_TRACK_ID}\t%X{USER_EMAIL}\t%message%n</pattern>

**Comment by ttddyy** [comment]
Can you expand your question?
If you want to use MDC, you need to set the values to MDC in order to reference them.

**Comment by liuzzzz** [comment]
need implements CoreSubscriber  please see  the source code of ReactorSleuth from 。about reactive tracing

**Comment by DmitriyKolusenko** [comment]
> You need to implement CoreSubscriber yourself, refer to the implementation in ReactorSleuth in SpringCloudSleuth. Be careful to use Threadlocal or MDC in the implementation class of CoreSubscriber

Liuzzz, Is the SpringCloudSleuth can help to thread safety forwarding MDC context to ProxyConnectionFactory.builder().onBeforeQuery() or maybe there is another way to do logging database request/response with MDC context?

**Comment by liuzzzz** [comment]
Like this, define your own data container, subscriber, and use Hooks to
concatenate. But I'm not sure if that solves your problem

/**
 * @author liuzz
 * @date 2022/08/18
 */
public interface ILocalAttribute {
    <K, V> void setAttribute(K key, V val);

    <K, V> V getAttribute(K key);
    <K, V> V getAttribute(K key, V defaultValue);
}

public abstract class AbstractLocalAttribute implements Closeable,
ILocalAttribute {
    public static final AbstractLocalAttribute EMPTY = new
AbstractLocalAttribute() {
        @Override
        public <K, V> void setAttribute(K key, V val) {

        }

        @Override
        public <K, V> V getAttribute(K key) {
            return null;
        }

        @Override
        public <K, V> V getAttribute(K key, V defaultValue) {
            return defaultValue;
        }
    };
    private static final ThreadLocal<? super AbstractLocalAttribute>
LOCAL = new ThreadLocal<>();

    public static <T extends AbstractLocalAttribute> T nowLocal(){
        return (T)LOCAL.get();
    }

    public static <T extends AbstractLocalAttribute> void setLocal(T t){
        LOCAL.set(t);
    }
    private static AbstractLocalAttribute currentLocal(){
        AbstractLocalAttribute local = nowLocal();
        if (null == local){
            local = EMPTY;
        }
        return local;
    }
    @Override
    public void close() {
        forceClose();
    }

    public final void forceClose() {
        ThreadContext.remove(SLEUTH_TRACE_ID);
        ThreadContext.remove(SLEUTH_TRACE_ID_XB3);
        ThreadContext.remove(SLEUTH_SPAN_ID);
        ThreadContext.remove(SLEUTH_SPAN_ID_XB3);
        ThreadContext.remove(SLEUTH_PARENT_SPAN_ID);
        ThreadContext.remove(SLEUTH_PARENT_SPAN_ID_XB3);
        LOCAL.remove();
    }

}

/**
 * @author liuzz
 * @date 2022/04/22
 * 基于 reactor Context 投机取巧， 有很多不适用的地方
 * 在Controller 流程以外的地方使用  不保证可以取到数据
 */
public abstract class LocalAttribute extends AbstractLocalAttribute {
    private static final Object NULL = new Object();
    private Context context;

    protected LocalAttribute() {
        this.context = Context.empty();
    }

    protected LocalAttribute(LocalAttribute pre) {
        this.context = null == pre ? Context.empty() : pre.getContext();
    }



    public static LocalAttribute current() {
        LocalAttribute localAttribute = nowLocal();
        if (null == localAttribute) {
            return new LocalAttributeLocal();
        }
        return nowLocal();
    }

    public static LocalAttribute maybe(LocalAttribute localAttribute) {
        LocalAttribute cur = nowLocal();
        if (null != cur && cur.isSame(localAttribute)) {
            if (localAttribute instanceof Noop) {
                return localAttribute;
            }
            return new Noop(localAttribute);
        }
        LocalAttribute newScope;
        if (!(localAttribute instanceof Noop) && null != localAttribute) {
            newScope = localAttribute;
        } else {
            newScope = new LocalAttributeLocal(localAttribute);
        }
        Map<String, String> context =
newScope.getAttribute(ThreadContext.class);
        if (null == context) {
            context = Collections.emptyMap();
        }
        ThreadContext.putAll(context);
        setLocal(newScope);
        return newScope;
    }

    public static LocalAttribute maybe(ContextView contextView) {
        TraceContext traceContext =
contextView.getOrDefault(TraceContext.class, null);
        if (null != traceContext) {
            String traceId = traceContext.traceId();
            String spanId = traceContext.spanId();
            String parentId = traceContext.parentId();
            ThreadContext.put(SLEUTH_TRACE_ID, traceId);
            ThreadContext.put(SLEUTH_TRACE_ID_XB3, traceId);
            ThreadContext.put(SLEUTH_SPAN_ID, spanId);
            ThreadContext.put(SLEUTH_SPAN_ID_XB3, spanId);
            ThreadContext.put(SLEUTH_PARENT_SPAN_ID, parentId);
            ThreadContext.put(SLEUTH_PARENT_SPAN_ID_XB3, parentId);
        }

        LocalAttribute maybe = maybe((LocalAttribute)
contextView.getOrDefault(LocalAttribute.class, null));
        maybe.setAttribute(ThreadContext.class, ThreadContext.getContext());
        return maybe;
    }

    public abstract String name();

    public Context getContext() {
        return context;
    }

    @Override
    public <K, V> void setAttribute(K key, V val) {
        if (null == val) {
            this.context = context.put(key, NULL);
            return;
        }
        this.context = context.put(key, val);
    }

    @Override
    public <K, V> V getAttribute(K key) {
        Object orDefault = this.context.getOrDefault(key, NULL);
        return orDefault == NULL ? null : (V) orDefault;
    }

    @Override
    public <K, V> V getAttribute(K key, V defaultVal) {
        Object orDefault = this.context.getOrDefault(key, NULL);
        return orDefault == NULL ? defaultVal : (V) orDefault;
    }

    public boolean isSame(LocalAttribute other) {
        return null != other && this.getContext() == other.getContext();
    }

    private static class Noop extends LocalAttribute {
        private final LocalAttribute delegate;

        public Noop(LocalAttribute pre) {
            this.delegate = pre;
        }

        @Override
        public String name() {
            return "Noop";
        }

        @Override
        public <K, V> void setAttribute(K key, V val) {
            this.delegate.setAttribute(key, val);
        }

        @Override
        public <K, V> V getAttribute(K key) {
            return this.delegate.getAttribute(key);
        }

        @Override
        public <K, V> V getAttribute(K key, V defaultVal) {
            return this.delegate.getAttribute(key, defaultVal);
        }

        @Override
        public Context getContext() {
            return this.delegate.getContext();
        }

        @Override
        public void close() {

        }

        @Override
        public String toString() {
            return "AttributeNoop{" +
                    "context=" + this.delegate.getContext() +
                    '}';
        }
    }

    private static class LocalAttributeLocal extends LocalAttribute {
        public LocalAttributeLocal() {
        }

        public LocalAttributeLocal(LocalAttribute pre) {
            super(pre);
        }

        @Override
        public String name() {
            return "Local";
        }

        @Override
        public String toString() {
            return "AttributeLocal{" +
                    "context=" + getContext() +
                    '}';
        }

    }
}



/**
 * @author liuzz
 * @date 2022/04/22
 */
public class LocalAttributeSubscriber implements
CoreSubscriber<Object>, Subscription, Scannable,
Fuseable.QueueSubscription<Object> {

    private final CoreSubscriber<Object> actual;
    private Subscription s;

    public LocalAttributeSubscriber(CoreSubscriber actual) {
        this.actual = actual;
    }

    @Override
    public Context currentContext() {
        return this.actual.currentContext();
    }

    @Override
    public void request(long n) {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.s.request(n);
        }
    }

    @Override
    public void cancel() {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.s.cancel();
        }
    }

    @Override
    public void onSubscribe(Subscription s) {
        this.s = s;
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onSubscribe(this);
        }
    }

    @Override
    public void onNext(Object o) {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onNext(o);
        }
    }

    @Override
    public void onError(Throwable t) {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onError(t);
        }
    }

    @Override
    public void onComplete() {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onComplete();
        }
    }

    @Override
    public int requestFusion(int requestedMode) {
        return Fuseable.NONE;
    }

    @Override
    public Object poll() {
        return null;
    }

    @Override
    public int size() {
        return 0;
    }

    @Override
    public boolean isEmpty() {
        return true;
    }

    @Override
    public void clear() {

    }

    @Override
    public Object scanUnsafe(Attr key) {
        if (key == Attr.PARENT) {
            return this.s;
        }
        else if (key == Attr.RUN_STYLE) {
            return Attr.RunStyle.SYNC;
        }
        else {
            return key == Attr.ACTUAL ? this.actual : null;
        }
    }
}

class LocalHooksRefresh implements ApplicationListener<ContextRefreshedEvent> {

    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        Hooks.onEachOperator(Operators.liftPublisher(LocalAttributeMono::shouldDecorate,
liftPublisher()));
        Hooks.onLastOperator(Operators.liftPublisher(liftPublisher()));
        Schedulers.onScheduleHook(LocalAttribute.class.getName(), r -> {
            LocalAttribute current = LocalAttribute.current();
            return (Runnable) () -> {
                try (LocalAttribute maybe = LocalAttribute.maybe(current)) {
                    r.run();
                }
            };
        });
    }

}



Tadaya Tsuyukubo ***@***.***> 于2022年10月26日周三 02:52写道：

**Comment by liuzzzz** [comment]
> > You need to implement CoreSubscriber yourself, refer to the implementation in ReactorSleuth in SpringCloudSleuth. Be careful to use Threadlocal or MDC in the implementation class of CoreSubscriber
> 
> Liuzzz, Is the SpringCloudSleuth can help to thread safety forwarding MDC context to ProxyConnectionFactory.builder().onBeforeQuery() or maybe there is another way to do logging database request/response with MDC context?

For Spring's ReactorSleuth component, TraceId, SpanId and other information must be stored in the MDC or thread context, so that we can see the content of [xxx,xxx] in the Console. I mean you need to refer to the implementation of ReactorSleuth, and then implement it according to your own demands your own.

**Comment by liuzzzz** [comment]
> > > You need to implement CoreSubscriber yourself, refer to the implementation in ReactorSleuth in SpringCloudSleuth. Be careful to use Threadlocal or MDC in the implementation class of CoreSubscriber
> > 
> > 
> > Liuzzz, Is the SpringCloudSleuth can help to thread safety forwarding MDC context to ProxyConnectionFactory.builder().onBeforeQuery() or maybe there is another way to do logging database request/response with MDC context?
> 
> For Spring's ReactorSleuth component, TraceId, SpanId and other information must be stored in the MDC or thread context, so that we can see the content of [xxx,xxx] in the Console. I mean you need to refer to the implementation of ReactorSleuth, and then implement it according to your own demands your own.

Like this,
`/**
 * @author liuzz
 * @date 2022/04/22
 */
public class LocalAttributeSubscriber implements CoreSubscriber<Object>, Subscription, Scannable, Fuseable.QueueSubscription<Object> {

    private final CoreSubscriber<Object> actual;
    private Subscription s;

    public LocalAttributeSubscriber(CoreSubscriber actual) {
        this.actual = actual;
    }

    @Override
    public Context currentContext() {
        return this.actual.currentContext();
    }

    @Override
    public void request(long n) {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.s.request(n);
        }
    }

    @Override
    public void cancel() {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.s.cancel();
        }
    }

    @Override
    public void onSubscribe(Subscription s) {
        this.s = s;
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onSubscribe(this);
        }
    }

    @Override
    public void onNext(Object o) {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onNext(o);
        }
    }

    @Override
    public void onError(Throwable t) {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onError(t);
        }
    }

    @Override
    public void onComplete() {
        try (LocalAttribute attr = LocalAttribute.maybe(currentContext())) {
            this.actual.onComplete();
        }
    }

    @Override
    public int requestFusion(int requestedMode) {
        return Fuseable.NONE;
    }

    @Override
    public Object poll() {
        return null;
    }

    @Override
    public int size() {
        return 0;
    }

    @Override
    public boolean isEmpty() {
        return true;
    }

    @Override
    public void clear() {

    }

    @Override
    public Object scanUnsafe(Attr key) {
        if (key == Attr.PARENT) {
            return this.s;
        }
        else if (key == Attr.RUN_STYLE) {
            return Attr.RunStyle.SYNC;
        }
        else {
            return key == Attr.ACTUAL ? this.actual : null;
        }
    }
}`
`
public abstract class AbstractLocalAttribute implements Closeable, ILocalAttribute {
    public static final AbstractLocalAttribute EMPTY = new AbstractLocalAttribute() {
        @Override
        public <K, V> void setAttribute(K key, V val) {

        }

        @Override
        public <K, V> V getAttribute(K key) {
            return null;
        }

        @Override
        public <K, V> V getAttribute(K key, V defaultValue) {
            return defaultValue;
        }
    };
    private static final ThreadLocal<? super AbstractLocalAttribute> LOCAL = new ThreadLocal<>();
}
`
The "LocalAttribute" contains field ThreadLocal
