### ISSUE TITLE
QueriesExecutionContext::isAllConsumed works different depending on signature of GenericExecuteSpec#map

### ISSUE THREAD

**Issue by Declow0** [r2dbc/r2dbc-proxy#138]
## Bug Report

Different variance of `map` method at `io.r2dbc.spi.Result` work inconsistently with `QueryInvocationSubscriber#afterQuery`

#### Versions

- Driver: io.r2dbc:r2dbc-h2:1.0.0.RELEASE
- Proxy: io.r2dbc:r2dbc-proxy:1.1.2.RELEASE 
- Database: H2
- Java: 17
- Kotlin: 1.8.22
- Kotlin Coroutines: 1.6.4
- OS: Mac OS Ventura 13.5.1

#### Current Behavior

```
io.r2dbc.spi.Result#map(java.util.function.Function<? super io.r2dbc.spi.Readable,? extends T>)
```

does not trigger `QueryInvocationSubscriber#afterQuery`

```
io.r2dbc.spi.Result#map(java.util.function.BiFunction<io.r2dbc.spi.Row,io.r2dbc.spi.RowMetadata,? extends T>)
```

triggers `QueryInvocationSubscriber#afterQuery`

#### Steps to reproduce

I have ProxyConnectionFactory with ObservationProxyExecutionListener

```kotlin
val url = "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1"
val connectionFactory = ConnectionFactoryBuilder
    .withUrl(url)
    .build()
ProxyConnectionFactory.builder(connectionFactory)
    .listener(
        ObservationProxyExecutionListener(ObservationRegistry.create(), connectionFactory, url).apply {
            setIncludeParameterValues(true)
        }
    )
    .build()
```

and repository

```kotlin
class Repository(
    private val databaseClient: DatabaseClient
) {
    suspend fun selectReadable(): Int? = Mono.usingWhen(
        databaseClient.connectionFactory.create(),
        { conn ->
            conn.createStatement("select 1").execute().toMono()
                .flatMap { result ->
                    result.map { readable ->
                        readable.get(0, Int::class.javaObjectType)
                    }.toMono()
                }
        },
        Connection::close
    ).awaitSingleOrNull()

    suspend fun selectBiFun(): Int? = Mono.usingWhen(
        databaseClient.connectionFactory.create(),
        { conn ->
            conn.createStatement("select 1").execute().toMono()
                .flatMap { result ->
                    result.map { row, _ ->
                        row.get(0, Int::class.javaObjectType)
                    }.toMono()
                }
        },
        Connection::close
    ).awaitSingleOrNull()
}
```

where `result` processed by different signatures of `GenericExecuteSpec#map`: Function or BiFunction as parameter.

When `selectReadable()` called then `QueryInvocationSubscriber#afterQuery` does not call because `io.r2dbc.proxy.callback.QueriesExecutionContext#isAllConsumed` is `false`.

Otherwise when `selectBiFun()` called then listener publishes `QueryInvocationSubscriber#afterQuery`

#### Expected behavior/code

Both variance of `io.r2dbc.spi.Result#map` trigger `QueryInvocationSubscriber#afterQuery`

**Comment by ttddyy** [comment]
@Declow0 Thanks for the report.

I'm a bit confused by `GenericExecuteSpec#map` but it essentially boils down to the `Result#map(BiFunction)` and `Result#map(Function)`.
I have root caused why it doesn't call `afterQuery`.  

It may take some time to implement this issue properly.
In the meantime, as a workaround, please use `Result#map(BiFunction)` to trigger the `afterQuery` for now.
