### ISSUE TITLE
Support comma separated "proxyListener" parameter in ConnectionFactoryProvider

### ISSUE THREAD

**Issue by ttddyy** [r2dbc/r2dbc-proxy#17]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

## Background
R2DBC's `ConnectionFactories` is the gateway to obtain a `ConnectionFactory` from a `ConnectionFactoryOptions` object. `ConnectionFactoryOptions` is a configuration object that holds the connection configuration in order to obtain a `ConnectionFactory` from the appropriate driver.

In `r2dbc-proxy`, [`io.r2dbc.proxy.ProxyConnectionFactoryProvider`][ProxyConnectionFactoryProvider.java] is the class that receives `ConnectionFactoryOptions` and produce `ConnectionFactory`.

## Problem
`ConnectionFactoryOptions` can be constructed by parsing a connection URL string or by programmatically.

For example with this URL:
```
r2dbc:proxy:postgresql://user@pass:localhost:5432/test-db?proxyListener=com.example.ListenerA,com.example.ListenerB
```

The parser will generate an `Option` object where key is `proxyListener` and value is `String` of  `com.example.ListenerA,com.example.ListenerB`.

Current implementation of [`io.r2dbc.proxy.ProxyConnectionFactoryProvider`][ProxyConnectionFactoryProvider.java] is NOT supporting comma separated list of class names when it handles `proxyListener` parameter.

## Solution
[`io.r2dbc.proxy.ProxyConnectionFactoryProvider`][ProxyConnectionFactoryProvider.java] should accept comma separated `String` value for `proxyListener` parameter.

When `proxyListener` option value is a `String`, treat it as a comma separated list of listener class names.  Iterate over each of those listener class names. They need to be instantiated and registered as proxy listeners.

## Steps to fix

- [x] Claim this issue with a comment below and ask any clarifying questions you need.
- [ ]  Set up a repository locally following the [Contributing Guidelines](https://github.com/r2dbc/r2dbc-spi/blob/master/CONTRIBUTING.adoc).
- [ ]  Try to fix the issue following the steps above.
- [ ]  Commit your changes and start a pull request.

## Deliverables

- [ ]  Changed `io.r2dbc.proxy.ProxyConnectionFactoryProvider`
- [ ]  Changed unit test `io.r2dbc.proxy.ProxyConnectionFactoryProviderTest`
- [ ]  Changed `README.md` - description of connection discovery options

----
related PR: https://github.com/r2dbc/r2dbc-spi/pull/48
related issue: https://github.com/r2dbc/r2dbc-spi/issues/37

[ProxyConnectionFactoryProvider.java]: https://github.com/r2dbc/r2dbc-proxy/blob/master/src/main/java/io/r2dbc/proxy/ProxyConnectionFactoryProvider.java

**Comment by viartemev** [comment]
I can take it

**Comment by mp911de** [comment]
Great! Thank you. Please let us know if you have any questions.

**Comment by viartemev** [comment]
@ttddyy @mp911de  what is expected behavior in case a user specifies two identical listeners: `proxyListener=com.example.ListenerA,com.example.ListenerA`. 
Do we need to deduplicate it or handle it as a valid case?
In current implementation if a user sets a collection of listeners and it contains duplicates, they will be added to `CompositeProxyExecutionListener` and because listeners stores in ArrayList, the listener's logic will be executed as many times as there were duplicates.

**Comment by ttddyy** [comment]
Hi @viartemev 
Thanks for grabbing this issue.

I think it is ok to handle it as a valid configuration, and registers duplicates listeners.
I don't have a concrete usecase for registering same listeners, but rather than framework performs de-dupe, it is better to behave as what user specified.
