### ISSUE TITLE
Proxy mechanism to support converting bind marker

### ISSUE THREAD

**Issue by ttddyy** [r2dbc/r2dbc-proxy#26]
I am experimenting the decorator/proxy to convert custom bind markers to the one that target database can understand.

I have created [`bind-param-converter`](https://github.com/r2dbc/r2dbc-proxy/tree/bind-param-converter) branch and added preliminary implementation.
Based on the change, I have created a [sample impl](https://gist.github.com/ttddyy/9fd2010b4c3e828bf9dd00273c48154c) that performs parameter conversion.

## tl;dr

```
conn.createStatement("INSERT INTO names (first_name, last_name) VALUES (:FIRST:, :LAST:) ")
    .bind(":LAST:", "FOO")
    .bind(":IGNORE:", "will be ignored")
    .bind(":FIRST:", "foo")
    .execute()
```

becomes

```
Query:["INSERT INTO names (first_name, last_name) VALUES (?, ?) "] Bindings:[(foo,FOO)]
```

## Implementation

There are two intercepting points to consider for bind parameter substitution.

1. `Connection#createStatement(sql)`
Here needs to convert the given query by replacing the custom placeholder to actual placeholder that target database can understand.  
 e.g.: `INSERT INTO names VALUES ( :first_name, :last_name )`  => `INSERT INTO names VALUES ( ?, ? )`  
Additionally, construct a map that contains position information for placeholder to avoid parsing query at bind operations.
e.g.: `{"first_name":0,"last_name":1}`
Also, requires a way to pass this map to the bind operation callback.

2. `bind/bindNull` operations
When performing bind operations, callback should be able to alter the actual behavior including not performing binding at all.
e.g.: `stmt.bind(":first_name", "foo")` => `stmt.bind(0, "foo")`

In the branch commit, [`BindParameterConverter` ](https://github.com/r2dbc/r2dbc-proxy/commit/317530a993d522a8d01d3104036883af0e78e0b5#diff-4ddc58494ca8704c2939d124b0facd3dR29) is the interface for the above callbacks.

In the sample implementation, [NamedBindParameterConverter.java](https://gist.github.com/ttddyy/9fd2010b4c3e828bf9dd00273c48154c#file-namedbindparameterconverter-java) covers following usecases:

- Convert colon surrounded parameter(`:name:`) to `?`
- Pass the parameter-index map from `onCreateStatement` to `onBind`
- Convert placeholder specific parameters to position index based bindings
- When `:IGNORE:` is specified in bind key, skip performing actual bind. (Demonstrating skip behavior).
 

Need more polishing on the changes, but this is the first step for supporting bind marker replacement story in r2dbc-proxy.

cc @nebhale @mp911de

**Comment by mp911de** [comment]
Thanks for picking up on this loose end. JDBC users want probably a conversion of  `?` to `$1`/`@P1`. We have also another aspect that plays into that which is stream parameter reuse: 

```
conn.createStatement("INSERT INTO names (first_name, last_name) VALUES (:PARAM:, :PARAM:) ")
    .bind(":PARAM:", Blob.from(…))
    .execute()
```

In this case, native execution accepts a single blob and translates it into the right result. Bind marker conversion would likely try to consume the `Blob` twice if we go for identifiable bind markers. Anonymous bind markers (such as `?`) require users to specify individual items because they correlate by positional occurence.

**Comment by ttddyy** [comment]
With [current converter API](https://github.com/r2dbc/r2dbc-proxy/commit/317530a993d522a8d01d3104036883af0e78e0b5#diff-4ddc58494ca8704c2939d124b0facd3dR29), above bind operation can be translated like this in converter.

```
Blob blob = Blob.from(...);
stmt.bind("$0", blob);
stmt.bind("$1", blob);
```

So, single `stmt.bind(":PARAM:", Blob.from(…))` can be converted to multiple bind operations - `stmt.bind("$0", blob).bind("$1", blob)`.

Or, even query can be translated to `INSERT INTO names (first_name, last_name) VALUES ($0,$0)` and bind operation can perform `stmt.bind("$0", Blob.from(...))` if driver/database allow such query and operation.

There is interesting aspect in multiple parameter expansion (as above example) with `Blob`(or `Clob`).
As you mentioned, I think the Blob will be consumed twice. So, this wouldn't work if blob is not able to support multiple read. If driver supports such that blob can be reused in different parameter binding (when same Blob object is passed in different `bind` operation), then it would work.

At this converter level, it is still manipulating SPI.
So, after all, it's pretty much on the driver that how much support it has, and the implementation of this converter API transforms the user defined binding operations to the extent that driver can understand by performing pass-through, skip, or modifying originated bind operations.
