### ISSUE TITLE
Update changelog for 0.8.0.RELEASE

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-proxy#43]

**Comment by ttddyy** [comment]
@mp911de I just copy pasted closed issues for the milestone to CHANGELOG.
Is there any script to compile CHANGELOG entries?

**Comment by mp911de** [comment]
@gregturn did something for [H2](https://github.com/r2dbc/r2dbc-h2/blob/master/src/test/java/io/r2dbc/h2/util/ChangeLogReportGenerator.java) and [I have a script to inspect commits written in ruby](https://gist.github.com/mp911de/77a31bc495a48f38706a730363d7090a).

**Comment by mp911de** [comment]
FYI: I didn't solve this ticket as I wasn't sure whether there are changes that should go into `r2dbc-proxy`. We aim for a release of the drivers/pool/proxy on Wednesday.
